In [0]:
import numpy as np

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
arr1=np.arange(20).reshape(4,5)
def swap_cols(arr, frm, to):
    arr[:,[frm, to]] = arr[:,[to, frm]]

swap_cols(arr1, 0, 3)
print(arr1)
# Hint----> Fancy Indexing

[[ 3  1  2  0  4]
 [ 8  6  7  5  9]
 [13 11 12 10 14]
 [18 16 17 15 19]]


In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row
arr1=np.arange(20).reshape(4,5)
def swap_rows(arr, frm, to):
    arr[[frm, to],:] = arr[[to, frm],:]


swap_rows(arr1, 0, 3)
print(arr1)

[[15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]]


In [0]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2
col_mean = np.nanmean(arr2, axis = 0)
print ("columns mean", str(col_mean))            #with column mean
inds = np.where(np.isnan(arr2))
arr2[inds] = np.take(col_mean, inds[1]) 
print ("final array", arr2)

columns mean [2.5 3.5 7.5]
final array [[1.  2.  7.5]
 [4.  5.  6. ]
 [2.5 3.5 9. ]]


In [0]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[78,  1, 77, 77],
       [56, 43, 48, 66],
       [86, 97, 85, 41],
       [54, 36, 77,  1],
       [43, 31, 36,  7]])

In [0]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3
arr3[ (arr3%3==0) | (arr3>25)]



array([77, 63, 71, 80, 92, 32, 78, 64, 43, 96, 70, 26, 75, 66, 70, 21, 33,
       30])

In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [0]:

print("\n 10th percentile of arr3,axis=none:",np.percentile(arr3,10))
print("\n50th Percentile of arr3, axis = None : ",  
      np.percentile(arr3, 50))  
print("\n25th Percentile of arr3, axis = None : ",  
      np.percentile(arr3, 25))  



 10th percentile of arr3,axis=none: 6.4

50th Percentile of arr3, axis = None :  51.0

25th Percentile of arr3, axis = None :  36.0
